project_name: rpasswd
dist: bin
build:
  main: main.go
  binary: rpasswd
  goos:
    - linux
    - darwin
    - windows
    - freebsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - ppc64le
  goarm:
    - 7
    - 6
    - 5
  ignore:
    - goos: darwin
      goarch: 386
    - goos: openbsd
      goarch: arm
    - goos: openbsd
      goarch: arm64
    - goos: freebsd
      goarch: arm64
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/joseluisq/rpasswd/cmd.versionNumber={{.Version}} -X github.com/joseluisq/rpasswd/cmd.buildTime={{.Date}}

archives:
  - id: rpasswd
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE-APACHE
      - LICENSE-MIT

release:
  prerelease: auto
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
signs:
  -
    cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
snapshot:
  name_template: "{{ .Tag }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
